---
# Playbook to deploy Ghost and its components
# TO DO

- name: Create namespace
  hosts: localhost
  gather_facts: false
  roles:
    - create_namespace

- name: Deploy MySQL
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_mysql

- name: Deploy Ghost
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_ghost

- name: Scaling MySQL
  hosts: localhost
  gather_facts: false
  roles:
    - scale_mysql
