---
# Playbook to undeploy Ghost and its components

- name: Undeploy Ghost
  hosts: localhost
  gather_facts: false
  roles:
      - { role: delete_ghost }
      - { role: delete_db, when: "delete_data is defined and delete_data=='true'"}